project:
  type: website
  output-dir: docs
website:
  title: "Blog"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - tech_articles.qmd
      - literature.qmd
      
  page-footer: 
    left: "Copyright 2024, Hitesh Kayastha" 
    background: light
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


